<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Resources\Minesweeper\Minesweeper1.png" Link="Assets\Minesweeper1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper2.png" Link="Assets\Minesweeper2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper3.png" Link="Assets\Minesweeper3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper4.png" Link="Assets\Minesweeper4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper5.png" Link="Assets\Minesweeper5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper6.png" Link="Assets\Minesweeper6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper7.png" Link="Assets\Minesweeper7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeper8.png" Link="Assets\Minesweeper8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeperbomb.png" Link="Assets\Minesweeperbomb.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeperflag.png" Link="Assets\Minesweeperflag.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeperreward.png" Link="Assets\Minesweeperreward.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweepersel.png" Link="Assets\Minesweepersel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Resources\Minesweeper\Minesweeperunsel.png" Link="Assets\Minesweeperunsel.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Milestone1\MineSweeperClassLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

</Project>